services:
  broker:
    image: eclipse-mosquitto
    container_name: broker
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
    networks:
      mqtt-net:
        ipv4_address: 192.168.21.10

networks:
  mqtt-net:
    external: true