[[inputs.mqtt_consumer]]
  servers = ["tcp://broker:1883"]  # Имя сервиса брокера
  topics = [
    "sensors/#"
  ]
  data_format = "value"
  data_type = "float"

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]  # Имя сервиса InfluxDB
  database = "sensors"
  skip_database_creation = true
  username = "telegraf"
  password = "telegraf"